pipeline:
  build:
    image: docker
    commands:
      - docker build -t php-sqlsrv -f docker/sql-server docker
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker:/var/lib/docker
  cache_restore:
    image: plugins/sftp-cache
    path: /var/cache/drone
    restore: true
    mount:
      - /composer/cache
  install:
      image: composer/composer
      commands:
        - composer install
  cache_rebuild:
      image: plugins/sftp-cache
      path: /var/cache/drone
      rebuild: true
      mount:
        - /composer/cache
  test:
    image: php-sqlsrv
    commands:
      - vendor/bin/phpunit -c tests/travis/${DRIVER}.travis.xml

services:
  db:
    image: ${DATABASE}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=D0ctrine

matrix:
  PHP:
    - 7.0
  DRIVER:
    - sqlsrv
    #- pdo_sqlsrv
  DATABASE:
    - microsoft/mssql-server-linux
