pipeline:
  build:
    image: plugins/docker
    repo: php-sqlsrv
    dockerfile: /docker/sql-server
    context: ./docker
  test:
    image: php-sqlsrv
    commands:
      - vendor/bin/phpunit -c tests/travis/${DRIVER}.travis.xml

services:
  database:
    image: ${DATABASE}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=doctrine

matrix:
  PHP:
    - 7.0
  DRIVER:
    - sqlsrv
    - pdo_sqlsrv
  DATABASE:
    - microsoft/mssql-server-linux


