pipeline:
  install:
      image: composer/composer
      commands:
        - composer install
      volumes:
        - /tmp/composer:/composer/cache
  test:
    image: deeky666/php:${PHP}
    commands:
      - php ${ADDITIONAL_ARGS} -d extension=sqlite3.so -d extension=pdo.so -d extension=pdo_sqlite.so -d extension=${DRIVER}${DRIVER_VARIATION}.so vendor/bin/phpunit -c tests/drone/${DRIVER}.travis.xml

services:
  db:
    image: deeky666/${DATABASE}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=D0ctrine

matrix:
  include:
    - PHP: 7.0
      DATABASE: base
      DRIVER: pdo_sqlite

    - PHP: 7.0
      DATABASE: mysql:5.7
      DRIVER: pdo_mysql
      DRIVER_VARIATION: -mysqlnd
      ADDITONAL_ARGS: -d extension=mysqlnd.so

    - PHP: 7.0
      DATABASE: mysql:5.7
      DRIVER: pdo_mysql
      DRIVER_VARIATION: -libmysql

    - PHP: 7.0
      DATABASE: mysql:5.7
      DRIVER: mysqli
      DRIVER_VARIATION: -mysqlnd
      ADDITONAL_ARGS: -d extension=mysqlnd.so

    - PHP: 7.0
      DATABASE: mysql:5.7
      DRIVER: mysqli
      DRIVER_VARIATION: -libmysql

#  DATABASE:
#    - microsoft/mssql-server-linux
