pipeline:
  build:
    image: php-sqlsrv
    commands:
      - vendor/bin/phpunit -c tests/travis/${DRIVER}.travis.xml

matrix:
  PHP:
    - 7.0
  DRIVER:
    - sqlsrv
    - pdo_sqlsrv
  DATABASE:
    - microsoft/mssql-server-linux


