#sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=mysql
  - DB=pgsql POSTGRESQL_VERSION=9.1
  - DB=pgsql POSTGRESQL_VERSION=9.2
  - DB=pgsql POSTGRESQL_VERSION=9.3
  - DB=sqlite
  - DB=mysqli
  - DB=db2

#cache:
#  directories:
#    - vendor
#    - $HOME/.composer/cache

before_install:
  - composer self-update
  - sh -c "if [ '$DB' = 'db2' ]; then echo 'deb http://archive.canonical.com/ubuntu precise partner' | sudo tee -a /etc/apt/sources.list; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then echo 'deb-src http://archive.canonical.com/ubuntu precise partner' | sudo tee -a /etc/apt/sources.list; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get update -y; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get install -y db2exc; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo su - db2inst1 -c 'db2sampl; db2 activate db sample; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then echo 'db2inst1:doctrine' | sudo chpasswd; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then printf '/home/db2inst1/sqllib\n' | pecl install ibm_db2; fi"

install:
  - composer update --prefer-source

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo su - db2inst1 -c 'db2sampl; db2 activate db sample; db2 connect to SAMPLE'; fi"

script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml

matrix:
  allow_failures:
      - php: hhvm
        env: DB=pgsql POSTGRESQL_VERSION=9.1
      - php: hhvm
        env: DB=pgsql POSTGRESQL_VERSION=9.2
      - php: hhvm
        env: DB=pgsql POSTGRESQL_VERSION=9.3
      - php: hhvm
        env: DB=sqlite
      - php: hhvm
        env: DB=mysql
      - php: hhvm-nightly
  exclude:
      - php: hhvm
        env: DB=pgsql POSTGRESQL_VERSION=9.1 # driver currently unsupported by HHVM
      - php: hhvm
        env: DB=pgsql POSTGRESQL_VERSION=9.2 # driver currently unsupported by HHVM
      - php: hhvm
        env: DB=pgsql POSTGRESQL_VERSION=9.3 # driver currently unsupported by HHVM
      - php: hhvm-nightly
        env: DB=pgsql POSTGRESQL_VERSION=9.1 # driver currently unsupported by HHVM
      - php: hhvm-nightly
        env: DB=pgsql POSTGRESQL_VERSION=9.2 # driver currently unsupported by HHVM
      - php: hhvm-nightly
        env: DB=pgsql POSTGRESQL_VERSION=9.3 # driver currently unsupported by HHVM
