language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 7.0
      sudo: true
      dist: trusty
      services:
        - docker
      env: DB=sqlsrv
      before_install:
        - docker pull microsoft/mssql-server-linux
        - docker build -t doctrine/sql-server -f docker/sql-server docker/sql-server
        - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=doctrine' -p 1433:1433 --name=db -d microsoft/mssql-server-linux
        - docker run -v $(pwd):/doctrine doctrine/sql-server
      script: php -m

install:
  - travis_retry composer install

before_script:
  - if [ '$DB' = 'pgsql' ]; then sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION; fi

script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
